name: Build and Test on Alpine

on:
  push:
    branches: [ main, dev, develop ]
  pull_request:
    branches: [ main, dev, develop ]

jobs:
  Build-and-Test-on-Alpine:
    runs-on: ubuntu-24.04
    container:
      image: crystallang/crystal:latest-alpine
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Install build tools
      run: |
        apk add coreutils make gcc g++ cmake
        apk add python3 py3-pip py3-numpy py3-matplotlib
        rm /usr/bin/python
        ln -s /usr/bin/python3.10 /usr/bin/python
    - name: Build googletest
      run: |
        make ./googletest-master/build/lib/libgtest.a
    - name: Build SSTD
      run: |
        make FORCE_TO_MAKE_SSTD
    - name: Build SSTD TESTS
      run: |
        make FORCE_TO_MAKE_TEST_EXE
    - name: Build the others
      run: |
        make
    - name: Run tests
      run: |
        ./exe
