name: CI for tests on Ubuntu

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Install Python
      run: |
        rm -rf /usr/bin/pip
        ln -s /usr/bin/pip /usr/bin/pip3
        rm -rf /usr/bin/python
        ln -s /usr/bin/python /usr/bin/python3
        pip install numpy
        pip install matplotlib
    - name: Build googletest
      run: |
        make ./googletest-master/build/lib/libgtest.a
    - name: Build SSTD
      run: |
        make FORCE_SSTD
    - name: Build the others
      run: |
        make
    - name: Run tests
      run: |
        ./exe
